// hooks/useAuth.ts
import { useState, useEffect } from "react";
import { supabase } from "../lib/supabase";
import { Capacitor } from '@capacitor/core';
import { GoogleAuth } from '@codetrix-studio/capacitor-google-auth';
import { SignInWithApple } from '@capacitor-community/apple-sign-in'; // 🍎 애플 플러그인 추가

export function useAuth() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setUser(session?.user ?? null);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setUser(session?.user ?? null);
    });

    return () => subscription.unsubscribe();
  }, []);

  const signIn = async (provider: 'google' | 'github' | 'kakao' | 'twitter' | 'apple') => {
    
    // 🌟 [진단 1] 현재 기기를 무엇으로 인식하는지 확인
    const platform = Capacitor.getPlatform();
    // alert(`현재 플랫폼: ${platform}`); // 필요시 주석 해제하여 확인

    // 📱 [경로 A: 확실한 모바일(iOS/Android) 환경일 때]
    if (platform === 'ios' || platform === 'android') {
      if (provider === 'google') {
        try {
          GoogleAuth.initialize({
            clientId: '940214114936-ntu201nqn72ot3oefsnoc1v1ns9ii702.apps.googleusercontent.com', 
            scopes: ['profile', 'email'],
            grantOfflineAccess: true,
          });

          const googleUser = await GoogleAuth.signIn();
          
          if (googleUser.authentication.idToken) {
            
            // 🌟 복잡한 해독기(디코더) 삭제! 순수하게 토큰만 던집니다.
            const { data, error } = await supabase.auth.signInWithIdToken({
              provider: 'google',
              token: googleUser.authentication.idToken,
              // nonce 파라미터는 이제 안 씁니다!
            });

            if (error) {
              alert('Supabase 거절 사유: ' + error.message); 
              throw error;
            }
            
            return { data, error };
          }
        } catch (error: any) {
          console.error('Google Native Auth Error:', error);
          alert('로그인 실패: ' + (error.message || JSON.stringify(error)));
          return { data: null, error };
        }
      }

      // 🍎 애플 네이티브
      if (provider === 'apple') {
        try {
          const result = await SignInWithApple.authorize({
            clientId: 'com.yeahplus.auraootd',
            redirectURI: 'https://auraootd.com',
            scopes: 'email name',
          });

          const autoGeneratedNonce = (result.response as any).nonce;

          if (result.response && result.response.identityToken) {
            const { data, error } = await supabase.auth.signInWithIdToken({
              provider: 'apple',
              token: result.response.identityToken,
              nonce: autoGeneratedNonce,
            });
            if (error) throw error;
            return { data, error };
          }
        } catch (error) {
          console.error('Apple Native Auth Error:', error);
          return { data: null, error }; // 여기서도 멈춤!
        }
      }
    }

    // 💻 [경로 B: 위에서 안 걸러진 PC 웹이거나 카카오/깃허브일 때만 실행]
    alert('🚨 웹(OAuth) 브라우저 모드로 진입했습니다!'); // 아이폰 구글 로그인 시 이 알림이 뜨면 안 됩니다.

    const redirectUrl = typeof window !== "undefined" 
      ? `${window.location.origin}/home` 
      : "http://localhost:3000/home";

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: provider,
      options: { redirectTo: redirectUrl }
    });

    return { data, error };
  };

  // 🌟 이메일 매직 링크 & 심사관 프리패스 통합 엔진 (강화 버전)
  const signInWithEmail = async (rawEmail: string) => {
    // 1. 공백 제거 및 소문자 변환 (오타 방어)
    const email = rawEmail.trim().toLowerCase(); 

    // 2. [심사관 전용 프리패스 로직]
    if (email === "test@auraootd.com") {
      console.log("🛠️ 심사관 계정 진입 시도");
      
      const { data, error } = await supabase.auth.signInWithPassword({
        email: "test@auraootd.com",
        password: "Aura1234!", // 👆 위 Supabase 대시보드에서 만든 비밀번호
      });

      if (error) {
        // 🚨 에러의 진짜 원인을 팝업으로 띄워줍니다. (네트워크 에러로 퉁치지 않음)
        alert("심사관 로그인 실패: " + error.message);
        return { data: null, error };
      }

      // ✅ 로그인 성공 시: 매직링크 대기 화면으로 가지 않고 강제로 홈으로 꽂아버립니다.
      if (typeof window !== "undefined") {
        alert("심사관 계정으로 로그인되었습니다."); // 테스트용 알림 (성공 확인 후 지우셔도 됩니다)
        window.location.href = '/home'; 
      }
      return { data, error: null };
    }

    // 3. [일반 유저 로직] 기존 매직링크 발송
    const redirectUrl = typeof window !== "undefined" 
      ? `${window.location.origin}/home` 
      : "http://localhost:3000/home";

    const { data, error } = await supabase.auth.signInWithOtp({
      email,
      options: { emailRedirectTo: redirectUrl }
    });
    
    return { data, error };
  };

  const signOut = async () => { await supabase.auth.signOut(); };

  const saveInstagram = async (handle: string) => {
    if (!user) return;
    const { data, error } = await supabase.auth.updateUser({ data: { instagram: handle } });
    if (data?.user) setUser(data.user); 
    
    if (!error) {
      // 과거 게시물 아이디 동기화
      await supabase.from('aura_fashion_items').update({ uploader_ig: handle }).eq('user_id', user.id);
    }
  };

  // 🌟 반환 객체에 signInWithEmail 추가
  return { user, setUser, signIn, signInWithEmail, signOut, login: signIn, logout: signOut, saveInstagram };
}